identifier: st25dv_disco
name: ST ST25DV Discovery
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
ram: 192
flash: 1024
supported:
  - arduino_i2c
  - gpio
  - arduino_gpio
  - i2c
  - spi
  - arduino_spi
  - usb_device
vendor: st
